# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0652faa2e4227ca12250755687a2499b36309f866febd0eb03b5627da7fd83eee3c15a20f3ac6dcd50df25ae6deb7f8bd2c25eeceecc43555f37cd1ea068ef2

test:
  secret_key_base: e7fc86183688609dc4e0655086ba028f52dffd2fbf3b5af37caae27e681cec89808a345c391ff31583944b5a91acf600a1b291edb1a76be62f26af829c46ae03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
